# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Install minimal dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY package.json setup.py MANIFEST.in src/ src/

# Unbuffered python output
ENV PYTHONUNBUFFERED=1

CMD ["python", "-u", "src/main.py"]
